# Generated by Django 3.1.7 on 2021-02-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuNote',
            fields=[
                ('mn_queue', models.AutoField(primary_key=True, serialize=False)),
                ('mn_table', models.CharField(max_length=16)),
                ('mn_note', models.CharField(max_length=5000)),
            ],
        ),
    ]
