runtime: python39 # or another supported version

env: standard

default_expiration: "7d"

handlers:
- url: /static
  static_dir: static
- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  BUCKET_NAME: "typeit-backend"
  DJANGO_SETTINGS_MODULE: "config.settings"